import { useEffect, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { LogoIcon } from '../components/AppIcons';
import DashboardLink from '../components/DashboardLink';
import * as api from '../services/accountabilityApi';

type Tab = 'safety' | 'appeals' | 'alerts' | 'witness';
const categories = ['', 'corruption', 'bribery', 'dowry', 'harassment', 'extortion', 'land_grabbing', 'hazard', 'antisocial_activity', 'other'];
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function AccountabilityPage() {
  const user = JSON.parse(localStorage.getItem('user') ?? 'null') as { role?: string } | null;
  const [tab, setTab] = useState<Tab>('safety');
  const [safety, setSafety] = useState<api.SafetyCheckIn[]>([]); const [appeals, setAppeals] = useState<api.Appeal[]>([]);
  const [subscriptions, setSubscriptions] = useState<api.Subscription[]>([]); const [notifications, setNotifications] = useState<api.RegionalNotification[]>([]); const [witnesses, setWitnesses] = useState<api.WitnessContribution[]>([]);
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [safetyRef, setSafetyRef] = useState(''); const [scheduledFor, setScheduledFor] = useState(''); const [safetyMessage, setSafetyMessage] = useState('');
  const [appealRef, setAppealRef] = useState(''); const [appealReason, setAppealReason] = useState(''); const [requestedOutcome, setRequestedOutcome] = useState('');
  const [district, setDistrict] = useState('Dhaka'); const [category, setCategory] = useState('');
  const [witnessRef, setWitnessRef] = useState(''); const [relationship, setRelationship] = useState('Eyewitness'); const [statement, setStatement] = useState(''); const [evidenceUrl, setEvidenceUrl] = useState(''); const [consent, setConsent] = useState(false);

  const load = async () => {
    const [s, a, sub, n, w] = await Promise.all([api.getMySafety(), api.getMyAppeals(), api.getSubscriptions(), api.getRegionalNotifications(), api.getMyWitnesses()]);
    setSafety(s.checkIns); setAppeals(a.appeals); setSubscriptions(sub.subscriptions); setNotifications(n.notifications); setWitnesses(w.contributions);
  };
  useEffect(() => {
    if (!user) return;
    let active = true;
    void Promise.all([api.getMySafety(), api.getMyAppeals(), api.getSubscriptions(), api.getRegionalNotifications(), api.getMyWitnesses()])
      .then(([s, a, sub, n, w]) => { if (active) { setSafety(s.checkIns); setAppeals(a.appeals); setSubscriptions(sub.subscriptions); setNotifications(n.notifications); setWitnesses(w.contributions); } })
      .catch((reason: Error) => { if (active) setError(reason.message); });
    return () => { active = false; };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps
  if (!user) return <Navigate to="/login" replace />;
  const run = async (action: () => Promise<unknown>, success: string) => { setError(''); try { await action(); setMessage(success); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.'); } };
  const enableBrowserAlerts = async () => {
    if (!('Notification' in window)) { setError('Browser notifications are not supported here.'); return; }
    const permission = await Notification.requestPermission();
    if (permission === 'granted') { new Notification('Truth Uncovered alerts enabled', { body: 'Regional alerts will also remain available inside your dashboard.' }); setMessage('Browser notifications enabled on this device.'); }
    else setError('Browser notification permission was not granted.');
  };

  return <div className="min-h-screen bg-bg-dark text-on-surface font-inter">
    <header className="border-b border-white/10"><div className="max-w-[1100px] mx-auto min-h-16 px-6 py-3 flex items-center justify-between gap-4"><Link to="/" className="flex items-center gap-3">
            <LogoIcon />
            <span className="font-['Sora'] font-bold text-lg tracking-tight text-white">
              Truth <span className="text-[#ffb4a4]">Uncovered</span>
            </span>
          </Link><DashboardLink /></div></header>
    <main className="max-w-[1100px] mx-auto px-6 py-10"><p className="text-xs font-bold uppercase tracking-widest text-brand-teal">Protected Participation</p><h1 className="font-sora text-3xl font-bold text-white mt-2">Safety and Community Actions</h1>
      <div className="flex flex-wrap gap-2 mt-7 border-b border-white/10 pb-3">{(['safety','appeals','alerts','witness'] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab === item ? 'bg-brand-teal text-black' : 'border border-white/10 text-on-surface/60'}`}>{label(item)}</button>)}</div>
      {error && <p className="mt-5 text-sm text-brand-red">{error}</p>}{message && <p className="mt-5 p-4 border border-brand-teal/30 rounded-lg text-sm text-brand-teal">{message}</p>}
      {tab === 'safety' && <section className="grid lg:grid-cols-2 gap-6 mt-7"><form onSubmit={(e) => { e.preventDefault(); void run(() => api.createSafety({ caseReference: safetyRef, scheduledFor: new Date(scheduledFor).toISOString(), privateMessage: safetyMessage }), 'Safety check-in scheduled.'); }} className="border border-white/10 rounded-lg p-6 bg-white/[0.02]"><h2 className="font-sora font-bold text-white">Schedule Safety Check-In</h2><p className="text-xs text-on-surface/50 mt-2">Private messages are visible only to you and administrators.</p><input value={safetyRef} onChange={(e) => setSafetyRef(e.target.value)} placeholder="Case or report reference (optional)" className="field mt-4" /><input required type="datetime-local" value={scheduledFor} onChange={(e) => setScheduledFor(e.target.value)} className="field mt-3" /><textarea rows={4} value={safetyMessage} onChange={(e) => setSafetyMessage(e.target.value)} placeholder="Private safety context (optional)" className="field mt-3" /><button className="primary mt-4">Schedule Check-In</button></form><div className="space-y-3">{safety.length === 0 ? <Empty text="No safety check-ins scheduled." /> : safety.map((item) => <article key={item.check_in_id} className="panel"><div className="flex justify-between gap-3"><strong className="text-white">{label(item.status)}</strong><span className="text-xs text-on-surface/40">{new Date(item.scheduled_for).toLocaleString()}</span></div>{item.case_reference && <p className="ref">{item.case_reference}</p>}{['scheduled','missed','needs_help'].includes(item.status) && <div className="flex gap-2 mt-4"><button onClick={() => void run(() => api.respondSafety(item.check_in_id, 'safe', 'I am safe.'), 'Safety status updated.')} className="secondary">I am safe</button><button onClick={() => void run(() => api.respondSafety(item.check_in_id, 'needs_help', 'I need confidential assistance.'), 'Urgent assistance requested.')} className="danger">I need help</button></div>}{item.resolution_note && <p className="text-sm mt-3">{item.resolution_note}</p>}</article>)}</div></section>}
      {tab === 'appeals' && <section className="grid lg:grid-cols-2 gap-6 mt-7"><form onSubmit={(e) => { e.preventDefault(); void run(() => api.createAppeal({ caseReference: appealRef, reason: appealReason, requestedOutcome }), 'Appeal submitted.'); }} className="panel"><h2 className="font-sora font-bold text-white">Appeal a Case Outcome</h2><p className="text-xs text-on-surface/50 mt-2">Available after action is recorded or a case is closed.</p><input required value={appealRef} onChange={(e) => setAppealRef(e.target.value)} placeholder="Case or report reference" className="field mt-4" /><textarea required minLength={30} rows={6} value={appealReason} onChange={(e) => setAppealReason(e.target.value)} placeholder="Explain the grounds for appeal" className="field mt-3" /><input required minLength={10} value={requestedOutcome} onChange={(e) => setRequestedOutcome(e.target.value)} placeholder="Requested outcome" className="field mt-3" /><button className="primary mt-4">Submit Appeal</button></form><div className="space-y-3">{appeals.length === 0 ? <Empty text="No appeals submitted." /> : appeals.map((item) => <article key={item.reference_no} className="panel"><div className="flex justify-between"><strong className="text-white">{item.reference_no}</strong><span className="badge">{label(item.status)}</span></div><p className="text-sm mt-3">{item.reason}</p>{item.admin_notes && <p className="text-sm text-brand-teal mt-3">Decision: {item.admin_notes}</p>}</article>)}</div></section>}
      {tab === 'alerts' && <section className="grid lg:grid-cols-2 gap-6 mt-7"><div><form onSubmit={(e) => { e.preventDefault(); void run(() => api.createSubscription({ district, category, channel: 'in_app', frequency: 'instant' }), 'Regional alert subscription saved.'); }} className="panel"><h2 className="font-sora font-bold text-white">Regional Alert Subscription</h2><input required value={district} onChange={(e) => setDistrict(e.target.value)} placeholder="District" className="field mt-4" /><select value={category} onChange={(e) => setCategory(e.target.value)} className="field mt-3"><option value="">All incident categories</option>{categories.slice(1).map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><p className="mt-3 text-xs text-on-surface/50">Matching public alerts are delivered instantly in the app.</p><div className="flex flex-wrap gap-2 mt-4"><button className="primary">Subscribe</button><button type="button" onClick={() => void enableBrowserAlerts()} className="secondary">Enable Browser Alerts</button></div></form><div className="space-y-2 mt-4">{subscriptions.map((item) => <div key={item.subscription_id} className="panel flex justify-between items-center gap-3"><span className="text-sm">{item.district} / {item.category ? label(item.category) : 'All categories'} / Instant</span><button onClick={() => void run(() => api.deleteSubscription(item.subscription_id), 'Subscription removed.')} className="danger">Remove</button></div>)}</div></div><div><h2 className="font-sora font-bold text-white mb-4">Regional Notifications</h2>{notifications.length === 0 ? <Empty text="No matching verified alerts yet." /> : notifications.map((item) => <button key={item.notification_id} onClick={() => void run(() => api.readRegionalNotification(item.notification_id), 'Notification marked read.')} className={`panel block w-full text-left mb-3 ${item.is_read ? 'opacity-50' : 'border-brand-teal/30'}`}><p className="text-sm">{item.message}</p><span className="text-xs text-on-surface/40">{new Date(item.created_at).toLocaleString()}</span></button>)}</div></section>}
      {tab === 'witness' && <section className="grid lg:grid-cols-2 gap-6 mt-7"><form onSubmit={(e) => { e.preventDefault(); void run(() => api.createWitness({ reportReference: witnessRef, relationship, statement, evidenceUrl, consentToContact: consent }), 'Confidential witness contribution submitted.'); }} className="panel"><h2 className="font-sora font-bold text-white">Confidential Witness Contribution</h2><p className="text-xs text-on-surface/50 mt-2">Your identity and statement never appear in the public repository.</p><input required value={witnessRef} onChange={(e) => setWitnessRef(e.target.value)} placeholder="Verified report reference" className="field mt-4" /><input required value={relationship} onChange={(e) => setRelationship(e.target.value)} placeholder="Relationship to incident" className="field mt-3" /><textarea required minLength={30} rows={7} value={statement} onChange={(e) => setStatement(e.target.value)} placeholder="Confidential witness statement" className="field mt-3" /><input type="url" value={evidenceUrl} onChange={(e) => setEvidenceUrl(e.target.value)} placeholder="HTTPS evidence link (optional)" className="field mt-3" /><label className="flex gap-3 text-sm mt-4"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} />Allow an administrator to contact me securely</label><button className="primary mt-4">Submit Contribution</button></form><div className="space-y-3">{witnesses.length === 0 ? <Empty text="No witness contributions submitted." /> : witnesses.map((item) => <article key={item.reference_no} className="panel"><div className="flex justify-between"><strong className="text-white">{item.reference_no}</strong><span className="badge">{label(item.status)}</span></div><p className="ref">Report {item.report_reference}</p><p className="text-sm mt-3">{item.relationship_to_incident}</p>{item.admin_notes && <p className="text-sm text-brand-teal mt-3">Review: {item.admin_notes}</p>}</article>)}</div></section>}
    </main>
  </div>;
}

function Empty({ text }: { text: string }) { return <div className="panel text-sm text-on-surface/50 text-center">{text}</div>; }
